/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

/**
 *
 * @author brene
 */
public class Reservas extends javax.swing.JFrame {

    /**
     * Creates new form Reservas
     */
    public Reservas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPasswordField1 = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelIconCafeGrande = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelSucuarsales = new javax.swing.JLabel();
        jLabelHorarios = new javax.swing.JLabel();
        jLabelEventos = new javax.swing.JLabel();
        jLabelMenu = new javax.swing.JLabel();
        jLabelReservas = new javax.swing.JLabel();
        jLabelTelefonos = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabelLetrasReserva = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabelMesa1 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanelMesas = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabelMesa2 = new javax.swing.JLabel();
        jLabelMesa3 = new javax.swing.JLabel();
        jLabelMesa4 = new javax.swing.JLabel();
        jLabelMesa5 = new javax.swing.JLabel();
        jLabelMesa6 = new javax.swing.JLabel();
        jLabelMesa7 = new javax.swing.JLabel();
        jLabelMesa8 = new javax.swing.JLabel();
        jLabelMesa9 = new javax.swing.JLabel();
        jLabelMesa10 = new javax.swing.JLabel();
        jLabelMesa11 = new javax.swing.JLabel();
        jLabelMesa12 = new javax.swing.JLabel();
        jLabelMesa13 = new javax.swing.JLabel();
        jLabelMesa14 = new javax.swing.JLabel();
        jLabelMesa15 = new javax.swing.JLabel();
        jLabelMesa16 = new javax.swing.JLabel();
        jLabelMesa17 = new javax.swing.JLabel();
        jLabelMesa18 = new javax.swing.JLabel();
        jLabelIconCafeGrande3 = new javax.swing.JLabel();
        jLabelIconCafeGrande2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelCerrar = new javax.swing.JLabel();
        jLabelMinimizar = new javax.swing.JLabel();
        jLabelBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.setPreferredSize(new java.awt.Dimension(290, 585));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo200.png"))); // NOI18N
        jPanel1.add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabelUsuario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(120, 77, 60));
        jLabelUsuario.setText("Usuario");
        jPanel1.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabelPassword.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(120, 77, 60));
        jLabelPassword.setText("Contraseña");
        jPanel1.add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jTextFieldUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldUsuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldUsuario.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldUsuario.setBorder(null);
        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 210, 30));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 220, 10));

        jPasswordField1.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setBorder(null);
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 180, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 220, 10));

        jLabelIconCafeGrande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cafe128.png"))); // NOI18N
        jPanel1.add(jLabelIconCafeGrande, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, -1, -1));

        jButton1.setBackground(new java.awt.Color(120, 77, 60));
        jButton1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ENVIAR");
        jButton1.setBorder(null);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 100, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(735, 535));
        jPanel2.setVerifyInputWhenFocusTarget(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSucuarsales.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSucuarsales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sucuarsales64Marron.png"))); // NOI18N
        jLabelSucuarsales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSucuarsalesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelSucuarsalesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelSucuarsalesMouseExited(evt);
            }
        });
        jPanel2.add(jLabelSucuarsales, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLabelHorarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/abierto64-64.png"))); // NOI18N
        jLabelHorarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHorariosMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelHorarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jLabelEventos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEventos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/evento64Marron.png"))); // NOI18N
        jLabelEventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEventosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelEventosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelEventosMouseExited(evt);
            }
        });
        jPanel2.add(jLabelEventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        jLabelMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu64-64.png"))); // NOI18N
        jLabelMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMenuMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, -1, -1));

        jLabelReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reservado64-64.png"))); // NOI18N
        jPanel2.add(jLabelReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        jLabelTelefonos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/llamada-telefonica64-64.png"))); // NOI18N
        jLabelTelefonos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTelefonosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelTelefonosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelTelefonosMouseExited(evt);
            }
        });
        jPanel2.add(jLabelTelefonos, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jSeparator5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(120, 77, 60), new java.awt.Color(120, 77, 60), new java.awt.Color(120, 77, 60), new java.awt.Color(120, 77, 60)));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 510, -1));

        jLabelLetrasReserva.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabelLetrasReserva.setForeground(new java.awt.Color(120, 77, 60));
        jLabelLetrasReserva.setText("Reservas");
        jPanel2.add(jLabelLetrasReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(148, 92, 60));
        jLabel10.setText("18");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, -1, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(148, 92, 60));
        jLabel11.setText("4");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(148, 92, 60));
        jLabel12.setText("5");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, -1, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(148, 92, 60));
        jLabel13.setText("6");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, -1, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(148, 92, 60));
        jLabel14.setText("10");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, -1, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(148, 92, 60));
        jLabel15.setText("11");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, -1, -1));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(148, 92, 60));
        jLabel16.setText("12");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, -1, -1));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(148, 92, 60));
        jLabel17.setText("16");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, -1, -1));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(148, 92, 60));
        jLabel18.setText("17");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, -1, -1));

        jLabelMesa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa 64.png"))); // NOI18N
        jLabelMesa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMesa1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMesa1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMesa1MouseExited(evt);
            }
        });
        jPanel2.add(jLabelMesa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(148, 92, 60));
        jLabel28.setText("15");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, -1, -1));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(148, 92, 60));
        jLabel29.setText("1");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(148, 92, 60));
        jLabel30.setText("2");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(148, 92, 60));
        jLabel31.setText("3");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(148, 92, 60));
        jLabel32.setText("7");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(148, 92, 60));
        jLabel33.setText("8");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, -1, -1));

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(148, 92, 60));
        jLabel34.setText("9");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, -1));

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(148, 92, 60));
        jLabel35.setText("13");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(148, 92, 60));
        jLabel36.setText("14");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, -1, -1));

        jPanelMesas.setBackground(new java.awt.Color(206, 200, 197));
        jPanelMesas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBackground(new java.awt.Color(206, 200, 197));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel18.setBackground(new java.awt.Color(220, 204, 188));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel55.setBackground(new java.awt.Color(255, 255, 255));
        jLabel55.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("Domingo");
        jPanel18.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        jLabel56.setBackground(new java.awt.Color(255, 255, 255));
        jLabel56.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("Lunes");
        jPanel18.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel57.setBackground(new java.awt.Color(255, 255, 255));
        jLabel57.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("Martes");
        jPanel18.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel58.setBackground(new java.awt.Color(255, 255, 255));
        jLabel58.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("Miercoles");
        jPanel18.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jLabel59.setBackground(new java.awt.Color(255, 255, 255));
        jLabel59.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Jueves");
        jPanel18.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLabel60.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("Viernes");
        jPanel18.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jLabel61.setBackground(new java.awt.Color(255, 255, 255));
        jLabel61.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("Sábado");
        jPanel18.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        jPanel17.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 530, 70));

        jPanelMesas.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 530, 30));

        jLabelMesa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa 64.png"))); // NOI18N
        jLabelMesa2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMesa2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMesa2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMesa2MouseExited(evt);
            }
        });
        jPanelMesas.add(jLabelMesa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 25, -1, -1));

        jLabelMesa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa 64.png"))); // NOI18N
        jLabelMesa3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMesa3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMesa3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMesa3MouseExited(evt);
            }
        });
        jPanelMesas.add(jLabelMesa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 25, -1, -1));

        jLabelMesa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa 64.png"))); // NOI18N
        jLabelMesa4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMesa4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMesa4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMesa4MouseExited(evt);
            }
        });
        jPanelMesas.add(jLabelMesa4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 25, -1, -1));

        jLabelMesa5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa 64.png"))); // NOI18N
        jLabelMesa5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMesa5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMesa5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMesa5MouseExited(evt);
            }
        });
        jPanelMesas.add(jLabelMesa5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 25, -1, -1));

        jLabelMesa6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa 64.png"))); // NOI18N
        jLabelMesa6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMesa6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMesa6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMesa6MouseExited(evt);
            }
        });
        jPanelMesas.add(jLabelMesa6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 25, -1, -1));

        jLabelMesa7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa 64.png"))); // NOI18N
        jLabelMesa7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMesa7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMesa7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMesa7MouseExited(evt);
            }
        });
        jPanelMesas.add(jLabelMesa7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabelMesa8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa 64.png"))); // NOI18N
        jLabelMesa8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMesa8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMesa8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMesa8MouseExited(evt);
            }
        });
        jPanelMesas.add(jLabelMesa8, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 110, -1, -1));

        jLabelMesa9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa 64.png"))); // NOI18N
        jLabelMesa9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMesa9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMesa9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMesa9MouseExited(evt);
            }
        });
        jPanelMesas.add(jLabelMesa9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        jLabelMesa10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa 64.png"))); // NOI18N
        jLabelMesa10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMesa10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMesa10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMesa10MouseExited(evt);
            }
        });
        jPanelMesas.add(jLabelMesa10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        jLabelMesa11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa 64.png"))); // NOI18N
        jLabelMesa11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMesa11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMesa11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMesa11MouseExited(evt);
            }
        });
        jPanelMesas.add(jLabelMesa11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, -1));

        jLabelMesa12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa 64.png"))); // NOI18N
        jLabelMesa12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMesa12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMesa12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMesa12MouseExited(evt);
            }
        });
        jPanelMesas.add(jLabelMesa12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, -1, -1));

        jLabelMesa13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa 64.png"))); // NOI18N
        jLabelMesa13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMesa13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMesa13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMesa13MouseExited(evt);
            }
        });
        jPanelMesas.add(jLabelMesa13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabelMesa14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa 64.png"))); // NOI18N
        jLabelMesa14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMesa14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMesa14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMesa14MouseExited(evt);
            }
        });
        jPanelMesas.add(jLabelMesa14, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 200, -1, -1));

        jLabelMesa15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa 64.png"))); // NOI18N
        jLabelMesa15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMesa15MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMesa15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMesa15MouseExited(evt);
            }
        });
        jPanelMesas.add(jLabelMesa15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        jLabelMesa16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa 64.png"))); // NOI18N
        jLabelMesa16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMesa16MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMesa16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMesa16MouseExited(evt);
            }
        });
        jPanelMesas.add(jLabelMesa16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        jLabelMesa17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa 64.png"))); // NOI18N
        jLabelMesa17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMesa17MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMesa17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMesa17MouseExited(evt);
            }
        });
        jPanelMesas.add(jLabelMesa17, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, -1));

        jLabelMesa18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa 64.png"))); // NOI18N
        jLabelMesa18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMesa18MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMesa18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMesa18MouseExited(evt);
            }
        });
        jPanelMesas.add(jLabelMesa18, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, -1, -1));

        jPanel2.add(jPanelMesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 225, 610, 280));

        jLabelIconCafeGrande3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/granos-de-cafe 128.png"))); // NOI18N
        jPanel2.add(jLabelIconCafeGrande3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, -1, -1));

        jLabelIconCafeGrande2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/granos-de-cafe 128.png"))); // NOI18N
        jPanel2.add(jLabelIconCafeGrande2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(735, 50));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCerrar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrarMarron32.png"))); // NOI18N
        jLabelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseExited(evt);
            }
        });
        jPanel3.add(jLabelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 43, -1));

        jLabelMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimizarMarron32.png"))); // NOI18N
        jLabelMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMinimizarMouseExited(evt);
            }
        });
        jPanel3.add(jLabelMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 43, -1));

        jLabelBack.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back32Marron.png"))); // NOI18N
        jLabelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBackMouseExited(evt);
            }
        });
        jPanel3.add(jLabelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jLabelBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMouseClicked
        Login volverLogin = new Login();
        volverLogin.setVisible(true);
        volverLogin.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelBackMouseClicked

    private void jLabelTelefonosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTelefonosMouseClicked
        Telefonos abrir = new Telefonos();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(this);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelTelefonosMouseClicked

    private void jLabelMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMenuMouseClicked
        Carta abrir = new Carta();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelMenuMouseClicked

    private void jLabelEventosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEventosMouseClicked
        Eventos abrir = new Eventos();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);

    }//GEN-LAST:event_jLabelEventosMouseClicked

    private void jLabelHorariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHorariosMouseClicked
        Horarios abrir = new Horarios();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelHorariosMouseClicked

    private void jLabelSucuarsalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSucuarsalesMouseClicked
        Sucursales abrir = new Sucursales();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelSucuarsalesMouseClicked

    private void jLabelMesa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa1MouseClicked
        Mesa1 abrir = new Mesa1();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelMesa1MouseClicked

    private void jLabelCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseEntered
         jLabelCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar32MarronClaro.png")));
    }//GEN-LAST:event_jLabelCerrarMouseEntered

    private void jLabelCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseExited
         jLabelCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrarMarron32.png")));
    }//GEN-LAST:event_jLabelCerrarMouseExited

    private void jLabelMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizarMouseEntered
        jLabelMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimizar32MarronClaro.png")));
    }//GEN-LAST:event_jLabelMinimizarMouseEntered

    private void jLabelMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizarMouseExited
        jLabelMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimizarMarron32.png")));
    }//GEN-LAST:event_jLabelMinimizarMouseExited

    private void jLabelBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMouseEntered
        jLabelBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back32MarronClaro.png")));
    }//GEN-LAST:event_jLabelBackMouseEntered

    private void jLabelBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMouseExited
        jLabelBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back32Marron.png")));
    }//GEN-LAST:event_jLabelBackMouseExited

    private void jLabelSucuarsalesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSucuarsalesMouseEntered
        jLabelSucuarsales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sucuarsales64MarronClaro.png")));
    }//GEN-LAST:event_jLabelSucuarsalesMouseEntered

    private void jLabelSucuarsalesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSucuarsalesMouseExited
        jLabelSucuarsales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sucuarsales64MarronClaro.png")));
    }//GEN-LAST:event_jLabelSucuarsalesMouseExited

    private void jLabelTelefonosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTelefonosMouseEntered
        jLabelTelefonos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/llamada-telefonica64MarronClaro.png")));
    }//GEN-LAST:event_jLabelTelefonosMouseEntered

    private void jLabelTelefonosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTelefonosMouseExited
        jLabelTelefonos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/llamada-telefonica64.png")));
    }//GEN-LAST:event_jLabelTelefonosMouseExited

    private void jLabelEventosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEventosMouseEntered
        jLabelEventos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/evento64MarronClaro.png")));
    }//GEN-LAST:event_jLabelEventosMouseEntered

    private void jLabelEventosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEventosMouseExited
        jLabelEventos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/evento64Marron.png")));
    }//GEN-LAST:event_jLabelEventosMouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setBackground(new java.awt.Color(150, 90, 25));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setBackground(new java.awt.Color(120, 77, 60));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabelMesa1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa1MouseEntered
        jLabelMesa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa64Marron.png")));
    }//GEN-LAST:event_jLabelMesa1MouseEntered

    private void jLabelMesa1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa1MouseExited
        jLabelMesa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa 64.png")));
    }//GEN-LAST:event_jLabelMesa1MouseExited

    private void jLabelMesa2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa2MouseClicked
        
    }//GEN-LAST:event_jLabelMesa2MouseClicked

    private void jLabelMesa2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa2MouseEntered
        jLabelMesa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa64Marron.png")));
    }//GEN-LAST:event_jLabelMesa2MouseEntered

    private void jLabelMesa2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa2MouseExited
        jLabelMesa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa 64.png")));
    }//GEN-LAST:event_jLabelMesa2MouseExited

    private void jLabelMesa3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelMesa3MouseClicked

    private void jLabelMesa3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa3MouseEntered
        jLabelMesa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa64Marron.png")));
    }//GEN-LAST:event_jLabelMesa3MouseEntered

    private void jLabelMesa3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa3MouseExited
        jLabelMesa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa 64.png")));
    }//GEN-LAST:event_jLabelMesa3MouseExited

    private void jLabelMesa4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelMesa4MouseClicked

    private void jLabelMesa4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa4MouseEntered
        jLabelMesa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa64Marron.png")));
    }//GEN-LAST:event_jLabelMesa4MouseEntered

    private void jLabelMesa4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa4MouseExited
        jLabelMesa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa 64.png")));
    }//GEN-LAST:event_jLabelMesa4MouseExited

    private void jLabelMesa5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelMesa5MouseClicked

    private void jLabelMesa5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa5MouseEntered
        jLabelMesa5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa64Marron.png")));
    }//GEN-LAST:event_jLabelMesa5MouseEntered

    private void jLabelMesa5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa5MouseExited
        jLabelMesa5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa 64.png")));
    }//GEN-LAST:event_jLabelMesa5MouseExited

    private void jLabelMesa6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelMesa6MouseClicked

    private void jLabelMesa6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa6MouseEntered
        jLabelMesa6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa64Marron.png")));
    }//GEN-LAST:event_jLabelMesa6MouseEntered

    private void jLabelMesa6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa6MouseExited
        jLabelMesa6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa 64.png")));
    }//GEN-LAST:event_jLabelMesa6MouseExited

    private void jLabelMesa7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelMesa7MouseClicked

    private void jLabelMesa7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa7MouseEntered
        jLabelMesa7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa64Marron.png")));
    }//GEN-LAST:event_jLabelMesa7MouseEntered

    private void jLabelMesa7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa7MouseExited
        jLabelMesa7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa 64.png")));
    }//GEN-LAST:event_jLabelMesa7MouseExited

    private void jLabelMesa8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelMesa8MouseClicked

    private void jLabelMesa8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa8MouseEntered
        jLabelMesa8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa64Marron.png")));
    }//GEN-LAST:event_jLabelMesa8MouseEntered

    private void jLabelMesa8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa8MouseExited
        jLabelMesa8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa 64.png")));
    }//GEN-LAST:event_jLabelMesa8MouseExited

    private void jLabelMesa9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa9MouseClicked
        
    }//GEN-LAST:event_jLabelMesa9MouseClicked

    private void jLabelMesa9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa9MouseEntered
        jLabelMesa9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa64Marron.png")));
    }//GEN-LAST:event_jLabelMesa9MouseEntered

    private void jLabelMesa9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa9MouseExited
        jLabelMesa9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa 64.png")));
    }//GEN-LAST:event_jLabelMesa9MouseExited

    private void jLabelMesa10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelMesa10MouseClicked

    private void jLabelMesa10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa10MouseEntered
       jLabelMesa10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa64Marron.png")));
    }//GEN-LAST:event_jLabelMesa10MouseEntered

    private void jLabelMesa10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa10MouseExited
        jLabelMesa10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa 64.png")));
    }//GEN-LAST:event_jLabelMesa10MouseExited

    private void jLabelMesa11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelMesa11MouseClicked

    private void jLabelMesa11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa11MouseEntered
        jLabelMesa11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa64Marron.png")));
    }//GEN-LAST:event_jLabelMesa11MouseEntered

    private void jLabelMesa11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa11MouseExited
        jLabelMesa11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa 64.png")));
    }//GEN-LAST:event_jLabelMesa11MouseExited

    private void jLabelMesa12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelMesa12MouseClicked

    private void jLabelMesa12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa12MouseEntered
        jLabelMesa12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa64Marron.png")));
        
    }//GEN-LAST:event_jLabelMesa12MouseEntered

    private void jLabelMesa12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa12MouseExited
        jLabelMesa12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa 64.png")));
    }//GEN-LAST:event_jLabelMesa12MouseExited

    private void jLabelMesa13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelMesa13MouseClicked

    private void jLabelMesa13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa13MouseEntered
        jLabelMesa13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa64Marron.png")));
    }//GEN-LAST:event_jLabelMesa13MouseEntered

    private void jLabelMesa13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa13MouseExited
        jLabelMesa13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa 64.png")));
    }//GEN-LAST:event_jLabelMesa13MouseExited

    private void jLabelMesa14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa14MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelMesa14MouseClicked

    private void jLabelMesa14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa14MouseEntered
        jLabelMesa14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa64Marron.png")));
    }//GEN-LAST:event_jLabelMesa14MouseEntered

    private void jLabelMesa14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa14MouseExited
        jLabelMesa14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa 64.png")));
    }//GEN-LAST:event_jLabelMesa14MouseExited

    private void jLabelMesa15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa15MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelMesa15MouseClicked

    private void jLabelMesa15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa15MouseEntered
       jLabelMesa15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa64Marron.png")));
    }//GEN-LAST:event_jLabelMesa15MouseEntered

    private void jLabelMesa15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa15MouseExited
        jLabelMesa15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa 64.png")));
    }//GEN-LAST:event_jLabelMesa15MouseExited

    private void jLabelMesa16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa16MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelMesa16MouseClicked

    private void jLabelMesa16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa16MouseEntered
        jLabelMesa16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa64Marron.png")));
    }//GEN-LAST:event_jLabelMesa16MouseEntered

    private void jLabelMesa16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa16MouseExited
        jLabelMesa16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa 64.png")));
    }//GEN-LAST:event_jLabelMesa16MouseExited

    private void jLabelMesa17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa17MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelMesa17MouseClicked

    private void jLabelMesa17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa17MouseEntered
        jLabelMesa17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa64Marron.png")));
    }//GEN-LAST:event_jLabelMesa17MouseEntered

    private void jLabelMesa17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa17MouseExited
        jLabelMesa17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa 64.png")));
    }//GEN-LAST:event_jLabelMesa17MouseExited

    private void jLabelMesa18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa18MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelMesa18MouseClicked

    private void jLabelMesa18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa18MouseEntered
        jLabelMesa18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa64Marron.png")));
    }//GEN-LAST:event_jLabelMesa18MouseEntered

    private void jLabelMesa18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMesa18MouseExited
        jLabelMesa18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa 64.png")));
    }//GEN-LAST:event_jLabelMesa18MouseExited

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabelBack;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JLabel jLabelEventos;
    private javax.swing.JLabel jLabelHorarios;
    private javax.swing.JLabel jLabelIconCafeGrande;
    private javax.swing.JLabel jLabelIconCafeGrande2;
    private javax.swing.JLabel jLabelIconCafeGrande3;
    private javax.swing.JLabel jLabelLetrasReserva;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelMenu;
    private javax.swing.JLabel jLabelMesa1;
    private javax.swing.JLabel jLabelMesa10;
    private javax.swing.JLabel jLabelMesa11;
    private javax.swing.JLabel jLabelMesa12;
    private javax.swing.JLabel jLabelMesa13;
    private javax.swing.JLabel jLabelMesa14;
    private javax.swing.JLabel jLabelMesa15;
    private javax.swing.JLabel jLabelMesa16;
    private javax.swing.JLabel jLabelMesa17;
    private javax.swing.JLabel jLabelMesa18;
    private javax.swing.JLabel jLabelMesa2;
    private javax.swing.JLabel jLabelMesa3;
    private javax.swing.JLabel jLabelMesa4;
    private javax.swing.JLabel jLabelMesa5;
    private javax.swing.JLabel jLabelMesa6;
    private javax.swing.JLabel jLabelMesa7;
    private javax.swing.JLabel jLabelMesa8;
    private javax.swing.JLabel jLabelMesa9;
    private javax.swing.JLabel jLabelMinimizar;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelReservas;
    private javax.swing.JLabel jLabelSucuarsales;
    private javax.swing.JLabel jLabelTelefonos;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelMesas;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
