/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

/**
 *
 * @author brene
 */
public class Telefonos extends javax.swing.JFrame {

    /**
     * Creates new form Horarios
     */
    public Telefonos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPasswordField1 = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelSucursales = new javax.swing.JLabel();
        jLabelEventos = new javax.swing.JLabel();
        jLabelReservas = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabelIconCafeGrande = new javax.swing.JLabel();
        jLabelLetrasTelefonosContactos = new javax.swing.JLabel();
        jLabelTelefonos1 = new javax.swing.JLabel();
        jLabelHorarios = new javax.swing.JLabel();
        jButtonClientes = new javax.swing.JButton();
        jButtonProveedores = new javax.swing.JButton();
        jButtonTrabajadores = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabelLetrasNombre = new javax.swing.JLabel();
        jLabelLetrasTelfMail = new javax.swing.JLabel();
        jLabelNumero1 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jLabelNombreLinea1 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel47 = new javax.swing.JLabel();
        jLabelWhatsappIcon = new javax.swing.JLabel();
        jLabelIconMail = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabelNumero2 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabelWhatsappIcon2 = new javax.swing.JLabel();
        jLabelIconMail2 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabelNumero3 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabelWhatsappIcon3 = new javax.swing.JLabel();
        jLabelIconMail3 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jPanelLinea3 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabelPassPage = new javax.swing.JLabel();
        jLabelBackPage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelIconCafeGrande1 = new javax.swing.JLabel();
        jLabelMenu = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelCerrar = new javax.swing.JLabel();
        jLabelMinimizar = new javax.swing.JLabel();
        jLabelBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1035, 580));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.setPreferredSize(new java.awt.Dimension(290, 585));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo200.png"))); // NOI18N
        jPanel1.add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabelUsuario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(120, 77, 60));
        jLabelUsuario.setText("Usuario");
        jPanel1.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabelPassword.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(120, 77, 60));
        jLabelPassword.setText("Contraseña");
        jPanel1.add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jTextFieldUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldUsuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldUsuario.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldUsuario.setBorder(null);
        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 210, 30));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 220, 10));

        jPasswordField1.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setBorder(null);
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 180, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 220, 10));

        jButton1.setBackground(new java.awt.Color(120, 77, 60));
        jButton1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ENVIAR");
        jButton1.setBorder(null);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 100, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(735, 535));
        jPanel2.setVerifyInputWhenFocusTarget(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSucursales.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSucursales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sucuarsales64Marron.png"))); // NOI18N
        jLabelSucursales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSucursalesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelSucursalesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelSucursalesMouseExited(evt);
            }
        });
        jPanel2.add(jLabelSucursales, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLabelEventos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEventos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/evento64Marron.png"))); // NOI18N
        jLabelEventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEventosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelEventosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelEventosMouseExited(evt);
            }
        });
        jPanel2.add(jLabelEventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jLabelReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reservado64Marron.png"))); // NOI18N
        jLabelReservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelReservasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelReservasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelReservasMouseExited(evt);
            }
        });
        jPanel2.add(jLabelReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, 70));

        jSeparator5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(120, 77, 60), new java.awt.Color(120, 77, 60), new java.awt.Color(120, 77, 60), new java.awt.Color(120, 77, 60)));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 510, -1));

        jLabelIconCafeGrande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/granos-de-cafe 128.png"))); // NOI18N
        jPanel2.add(jLabelIconCafeGrande, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, -1, -1));

        jLabelLetrasTelefonosContactos.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabelLetrasTelefonosContactos.setForeground(new java.awt.Color(120, 77, 60));
        jLabelLetrasTelefonosContactos.setText("Teléfonos y contactos");
        jPanel2.add(jLabelLetrasTelefonosContactos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        jLabelTelefonos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/llamada-telefonica48-48.png"))); // NOI18N
        jPanel2.add(jLabelTelefonos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabelHorarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/abierto64-64.png"))); // NOI18N
        jLabelHorarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHorariosMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelHorarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jButtonClientes.setBackground(new java.awt.Color(153, 153, 153));
        jButtonClientes.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jButtonClientes.setForeground(new java.awt.Color(255, 255, 255));
        jButtonClientes.setText("Clientes");
        jButtonClientes.setBorder(null);
        jButtonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClientesActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 100, 40));

        jButtonProveedores.setBackground(new java.awt.Color(120, 77, 60));
        jButtonProveedores.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jButtonProveedores.setForeground(new java.awt.Color(255, 255, 255));
        jButtonProveedores.setText("Proveedores");
        jButtonProveedores.setBorder(null);
        jButtonProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonProveedoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonProveedoresMouseExited(evt);
            }
        });
        jButtonProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProveedoresActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 100, 40));

        jButtonTrabajadores.setBackground(new java.awt.Color(153, 153, 153));
        jButtonTrabajadores.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jButtonTrabajadores.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTrabajadores.setText("Trabajadores");
        jButtonTrabajadores.setBorder(null);
        jButtonTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrabajadoresActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonTrabajadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 100, 40));

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(120, 77, 60));
        jLabel30.setText("Nº Socio");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        jLabelLetrasNombre.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelLetrasNombre.setForeground(new java.awt.Color(120, 77, 60));
        jLabelLetrasNombre.setText("Nombre");
        jPanel2.add(jLabelLetrasNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, -1));

        jLabelLetrasTelfMail.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelLetrasTelfMail.setForeground(new java.awt.Color(120, 77, 60));
        jLabelLetrasTelfMail.setText("Teléfonos / e-mail");
        jPanel2.add(jLabelLetrasTelfMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, -1));

        jLabelNumero1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabelNumero1.setForeground(new java.awt.Color(120, 77, 60));
        jLabelNumero1.setText("1");
        jPanel2.add(jLabelNumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 300, 10, -1));

        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 291, -1, 180));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 600, 10));

        jSeparator14.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 292, 10, 180));

        jLabelNombreLinea1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabelNombreLinea1.setForeground(new java.awt.Color(120, 77, 60));
        jLabelNombreLinea1.setText("José Perez Benítez");
        jPanel2.add(jLabelNombreLinea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        jSeparator15.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 292, 10, 180));

        jLabel47.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(120, 77, 60));
        jLabel47.setText("646 07 58 74                    j.perez@gmail.com");
        jPanel2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));

        jLabelWhatsappIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/whatsarron16.png"))); // NOI18N
        jLabelWhatsappIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelWhatsappIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelWhatsappIconMouseExited(evt);
            }
        });
        jPanel2.add(jLabelWhatsappIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, -1, -1));

        jLabelIconMail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/email.png"))); // NOI18N
        jLabelIconMail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelIconMailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelIconMailMouseExited(evt);
            }
        });
        jPanel2.add(jLabelIconMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, -1, -1));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 292, 10, 180));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 600, 10));

        jLabelNumero2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabelNumero2.setForeground(new java.awt.Color(120, 77, 60));
        jLabelNumero2.setText("2");
        jPanel2.add(jLabelNumero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 330, -1, -1));

        jLabel37.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(120, 77, 60));
        jLabel37.setText("Antonio Calvo Ruíz");
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));

        jLabel42.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(120, 77, 60));
        jLabel42.setText("654 45 85 69                    a.calvo@gmail.com");
        jPanel2.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, -1));

        jLabelWhatsappIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/whatsarron16.png"))); // NOI18N
        jLabelWhatsappIcon2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelWhatsappIcon2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelWhatsappIcon2MouseExited(evt);
            }
        });
        jPanel2.add(jLabelWhatsappIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, -1, -1));

        jLabelIconMail2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/email.png"))); // NOI18N
        jLabelIconMail2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelIconMail2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelIconMail2MouseExited(evt);
            }
        });
        jPanel2.add(jLabelIconMail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, -1, -1));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 600, -1));

        jLabelNumero3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabelNumero3.setForeground(new java.awt.Color(120, 77, 60));
        jLabelNumero3.setText("3");
        jPanel2.add(jLabelNumero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 360, -1, -1));

        jLabel38.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(120, 77, 60));
        jLabel38.setText("Frimar Climatizacion S.L");
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        jLabel43.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(120, 77, 60));
        jLabel43.setText("620 45 12 25                    info@frimarclima.com");
        jPanel2.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, -1, 20));

        jLabelWhatsappIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/whatsarron16.png"))); // NOI18N
        jLabelWhatsappIcon3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelWhatsappIcon3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelWhatsappIcon3MouseExited(evt);
            }
        });
        jPanel2.add(jLabelWhatsappIcon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, -1, -1));

        jLabelIconMail3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/email.png"))); // NOI18N
        jLabelIconMail3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelIconMail3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelIconMail3MouseExited(evt);
            }
        });
        jPanel2.add(jLabelIconMail3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, -1, -1));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 600, 10));
        jPanel2.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 600, 10));
        jPanel2.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 600, 10));
        jPanel2.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 600, 10));

        jPanelLinea3.setBackground(new java.awt.Color(206, 200, 197));
        jPanelLinea3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel20.setBackground(new java.awt.Color(220, 204, 188));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel62.setBackground(new java.awt.Color(255, 255, 255));
        jLabel62.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setText("Domingo");
        jPanel20.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        jLabel63.setBackground(new java.awt.Color(255, 255, 255));
        jLabel63.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("Lunes");
        jPanel20.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel64.setBackground(new java.awt.Color(255, 255, 255));
        jLabel64.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setText("Martes");
        jPanel20.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel65.setBackground(new java.awt.Color(255, 255, 255));
        jLabel65.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65.setText("Miercoles");
        jPanel20.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jLabel66.setBackground(new java.awt.Color(255, 255, 255));
        jLabel66.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setText("Jueves");
        jPanel20.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLabel67.setBackground(new java.awt.Color(255, 255, 255));
        jLabel67.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setText("Viernes");
        jPanel20.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jLabel68.setBackground(new java.awt.Color(255, 255, 255));
        jLabel68.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setText("Sábado");
        jPanel20.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        jPanelLinea3.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 530, 70));

        jPanel21.setBackground(new java.awt.Color(206, 200, 197));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel22.setBackground(new java.awt.Color(220, 204, 188));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel69.setBackground(new java.awt.Color(255, 255, 255));
        jLabel69.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setText("Domingo");
        jPanel22.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        jLabel70.setBackground(new java.awt.Color(255, 255, 255));
        jLabel70.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setText("Lunes");
        jPanel22.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel71.setBackground(new java.awt.Color(255, 255, 255));
        jLabel71.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setText("Martes");
        jPanel22.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel72.setBackground(new java.awt.Color(255, 255, 255));
        jLabel72.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setText("Miercoles");
        jPanel22.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jLabel73.setBackground(new java.awt.Color(255, 255, 255));
        jLabel73.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setText("Jueves");
        jPanel22.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLabel74.setBackground(new java.awt.Color(255, 255, 255));
        jLabel74.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setText("Viernes");
        jPanel22.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jLabel75.setBackground(new java.awt.Color(255, 255, 255));
        jLabel75.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(255, 255, 255));
        jLabel75.setText("Sábado");
        jPanel22.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        jPanel21.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 530, 70));

        jPanelLinea3.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 530, 30));

        jPanel2.add(jPanelLinea3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 620, 220));

        jLabelPassPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/siguiente-24-24.png"))); // NOI18N
        jLabelPassPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelPassPageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelPassPageMouseExited(evt);
            }
        });
        jPanel2.add(jLabelPassPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 495, -1, -1));

        jLabelBackPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anterior gris 16.png"))); // NOI18N
        jPanel2.add(jLabelBackPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 500, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/numero-1Marron32.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, -1, -1));

        jLabelIconCafeGrande1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/granos-de-cafe 128.png"))); // NOI18N
        jPanel2.add(jLabelIconCafeGrande1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, -1, -1));

        jLabelMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu64Marron.png"))); // NOI18N
        jLabelMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMenuMouseExited(evt);
            }
        });
        jPanel2.add(jLabelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(735, 50));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCerrar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrarMarron32.png"))); // NOI18N
        jLabelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseExited(evt);
            }
        });
        jPanel3.add(jLabelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 7, 43, -1));

        jLabelMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimizarMarron32.png"))); // NOI18N
        jLabelMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMinimizarMouseExited(evt);
            }
        });
        jPanel3.add(jLabelMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 3, 43, 40));

        jLabelBack.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back32Marron.png"))); // NOI18N
        jLabelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBackMouseExited(evt);
            }
        });
        jPanel3.add(jLabelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jLabelBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMouseClicked
        Login volverLogin = new Login();
        volverLogin.setVisible(true);
        volverLogin.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelBackMouseClicked

    private void jLabelSucursalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSucursalesMouseClicked
        Sucursales abrir = new Sucursales();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelSucursalesMouseClicked

    private void jLabelEventosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEventosMouseClicked
        Eventos abrir = new Eventos();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelEventosMouseClicked

    private void jLabelReservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelReservasMouseClicked
        Reservas abrir = new Reservas();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelReservasMouseClicked

    private void jLabelSucursalesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSucursalesMouseEntered
        jLabelSucursales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sucuarsales64MarronClaro.png")));
    }//GEN-LAST:event_jLabelSucursalesMouseEntered

    private void jLabelSucursalesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSucursalesMouseExited
      jLabelSucursales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sucuarsales64Marron.png")));
    }//GEN-LAST:event_jLabelSucursalesMouseExited

    private void jLabelCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseEntered
         jLabelCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar32MarronClaro.png")));
    }//GEN-LAST:event_jLabelCerrarMouseEntered

    private void jLabelCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseExited
         jLabelCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrarMarron32.png")));
    }//GEN-LAST:event_jLabelCerrarMouseExited

    private void jLabelMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizarMouseEntered
        jLabelMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimizar32MarronClaro.png")));
    }//GEN-LAST:event_jLabelMinimizarMouseEntered

    private void jLabelMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizarMouseExited
        jLabelMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimizarMarron32.png")));
    }//GEN-LAST:event_jLabelMinimizarMouseExited

    private void jLabelBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMouseEntered
        jLabelBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back32MarronClaro.png")));
    }//GEN-LAST:event_jLabelBackMouseEntered

    private void jLabelBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMouseExited
        jLabelBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back32Marron.png")));
    }//GEN-LAST:event_jLabelBackMouseExited

    private void jLabelHorariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHorariosMouseClicked
        Horarios abrir = new Horarios();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelHorariosMouseClicked

    private void jButtonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonClientesActionPerformed

    private void jButtonProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProveedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonProveedoresActionPerformed

    private void jButtonTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrabajadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTrabajadoresActionPerformed

    private void jLabelEventosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEventosMouseEntered
        jLabelEventos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/evento64MarronClaro.png")));
    }//GEN-LAST:event_jLabelEventosMouseEntered

    private void jLabelEventosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEventosMouseExited
        jLabelEventos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/evento64Marron.png")));
    }//GEN-LAST:event_jLabelEventosMouseExited

    private void jLabelReservasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelReservasMouseEntered
        jLabelReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reservado64MarronClaro.png")));
    }//GEN-LAST:event_jLabelReservasMouseEntered

    private void jLabelReservasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelReservasMouseExited
        jLabelReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reservado64Marron.png")));
    }//GEN-LAST:event_jLabelReservasMouseExited

    private void jLabelMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMenuMouseClicked
        Carta abrir = new Carta();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);

    }//GEN-LAST:event_jLabelMenuMouseClicked

    private void jLabelMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMenuMouseEntered
        jLabelMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu64MarronClaro.png")));
    }//GEN-LAST:event_jLabelMenuMouseEntered

    private void jLabelMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMenuMouseExited
        jLabelMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu64Marron.png")));
    }//GEN-LAST:event_jLabelMenuMouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setBackground(new java.awt.Color(150, 90, 25));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setBackground(new java.awt.Color(120, 77, 60));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonProveedoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonProveedoresMouseEntered
        jButtonProveedores.setBackground(new java.awt.Color(150, 90, 25));
    }//GEN-LAST:event_jButtonProveedoresMouseEntered

    private void jButtonProveedoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonProveedoresMouseExited
        jButtonProveedores.setBackground(new java.awt.Color(120, 77, 60));
    }//GEN-LAST:event_jButtonProveedoresMouseExited

    private void jLabelIconMailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconMailMouseEntered
        jLabelIconMail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/emailZoom.png")));
    }//GEN-LAST:event_jLabelIconMailMouseEntered

    private void jLabelIconMailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconMailMouseExited
        jLabelIconMail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/email.png")));
    }//GEN-LAST:event_jLabelIconMailMouseExited

    private void jLabelIconMail2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconMail2MouseEntered
      jLabelIconMail2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/emailZoom.png")));
    }//GEN-LAST:event_jLabelIconMail2MouseEntered

    private void jLabelIconMail2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconMail2MouseExited
        jLabelIconMail2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/email.png")));
    }//GEN-LAST:event_jLabelIconMail2MouseExited

    private void jLabelIconMail3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconMail3MouseEntered
       jLabelIconMail3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/emailZoom.png")));
    }//GEN-LAST:event_jLabelIconMail3MouseEntered

    private void jLabelIconMail3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconMail3MouseExited
        jLabelIconMail3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/email.png")));
    }//GEN-LAST:event_jLabelIconMail3MouseExited

    private void jLabelWhatsappIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelWhatsappIconMouseEntered
        jLabelWhatsappIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/whatsappMarron24.png")));
    }//GEN-LAST:event_jLabelWhatsappIconMouseEntered

    private void jLabelWhatsappIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelWhatsappIconMouseExited
        jLabelWhatsappIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/whatsarron16.png")));
    }//GEN-LAST:event_jLabelWhatsappIconMouseExited

    private void jLabelWhatsappIcon2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelWhatsappIcon2MouseEntered
        jLabelWhatsappIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/whatsappMarron24.png")));
    }//GEN-LAST:event_jLabelWhatsappIcon2MouseEntered

    private void jLabelWhatsappIcon2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelWhatsappIcon2MouseExited
        jLabelWhatsappIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/whatsarron16.png")));
    }//GEN-LAST:event_jLabelWhatsappIcon2MouseExited

    private void jLabelWhatsappIcon3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelWhatsappIcon3MouseEntered
       jLabelWhatsappIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/whatsappMarron24.png")));
    }//GEN-LAST:event_jLabelWhatsappIcon3MouseEntered

    private void jLabelWhatsappIcon3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelWhatsappIcon3MouseExited
       jLabelWhatsappIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/whatsarron16.png")));
    }//GEN-LAST:event_jLabelWhatsappIcon3MouseExited

    private void jLabelPassPageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPassPageMouseEntered
        jLabelPassPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/siguiente-24-24Zoom.png")));
    }//GEN-LAST:event_jLabelPassPageMouseEntered

    private void jLabelPassPageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPassPageMouseExited
        jLabelPassPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/siguiente-24-24.png")));
    }//GEN-LAST:event_jLabelPassPageMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonClientes;
    private javax.swing.JButton jButtonProveedores;
    private javax.swing.JButton jButtonTrabajadores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabelBack;
    private javax.swing.JLabel jLabelBackPage;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JLabel jLabelEventos;
    private javax.swing.JLabel jLabelHorarios;
    private javax.swing.JLabel jLabelIconCafeGrande;
    private javax.swing.JLabel jLabelIconCafeGrande1;
    private javax.swing.JLabel jLabelIconMail;
    private javax.swing.JLabel jLabelIconMail2;
    private javax.swing.JLabel jLabelIconMail3;
    private javax.swing.JLabel jLabelLetrasNombre;
    private javax.swing.JLabel jLabelLetrasTelefonosContactos;
    private javax.swing.JLabel jLabelLetrasTelfMail;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelMenu;
    private javax.swing.JLabel jLabelMinimizar;
    private javax.swing.JLabel jLabelNombreLinea1;
    private javax.swing.JLabel jLabelNumero1;
    private javax.swing.JLabel jLabelNumero2;
    private javax.swing.JLabel jLabelNumero3;
    private javax.swing.JLabel jLabelPassPage;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelReservas;
    private javax.swing.JLabel jLabelSucursales;
    private javax.swing.JLabel jLabelTelefonos1;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLabelWhatsappIcon;
    private javax.swing.JLabel jLabelWhatsappIcon2;
    private javax.swing.JLabel jLabelWhatsappIcon3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelLinea3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
